name: Bug Report
description: Existing feature does not behave as expected
lables: Bug
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use?"
      options:
        - Windows 7
        - Windows 8
        - Windows 10
        - Windows 11
        - Other windows version. (please specify in the description!)
    validations:
      required: true 
  - type: dropdown
    id: systemlang
    attributes:
      label: Systemlanguage
      description: "Which system language do you use?"
      options:
        - German (DE)
        - English (EN)
        - Russian (RU)
        - Other windows language. (please specify in the description!)
    validations:
      required: true 
  - type: input
    id: gameversion
    attributes:
      label: Current Game-Version
      description: "Please provide the current game version you use."
      placeholder: "v2.9.1.4"
    validations:
      required: true
  - type: input
    id: php
    attributes:
      label: PHP Version
      description: "Please provide the full PHP version that is powering Tinkerwell."
      placeholder: "PHP 8.0.7, built: Jun  4 2021 01:50:04"
    validations:
      required: true
  
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Please describe the bug you experience as precisely as possible.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
